# Generated by Django 4.2 on 2023-04-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default=False),
        ),
    ]
