# Generated by Django 4.2 on 2023-04-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_age_user_gender_user_introduction_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=False, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.TextField(default=False, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(default=False, verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(default=False, verbose_name='username'),
        ),
    ]
