# Generated by Django 4.2 on 2023-04-28 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='업데이트시간')),
                ('is_complete', models.BooleanField(default=False, verbose_name='완료여부')),
                ('completion_at', models.DateField(blank=True, null=True, verbose_name='완료시간')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
        ),
    ]
